#!/bin/bash

qsub agincm-fit1.pbs
qsub agincf-fit1.pbs
qsub karongam-fit1.pbs
qsub karongaf-fit1.pbs
qsub kisesam-fit1.pbs
qsub kisesaf-fit1.pbs
qsub kisumum-fit1.pbs
qsub kisumuf-fit1.pbs
qsub manicm-fit1.pbs
qsub manicf-fit1.pbs
qsub masakam-fit1.pbs
qsub masakaf-fit1.pbs
qsub rakaim-fit1.pbs
qsub rakaif-fit1.pbs
qsub umkhanm-fit1.pbs
qsub umkhanf-fit1.pbs

qsub agincm-fit2.pbs
qsub agincf-fit2.pbs
qsub karongam-fit2.pbs
qsub karongaf-fit2.pbs
qsub kisesam-fit2.pbs
qsub kisesaf-fit2.pbs
qsub kisumum-fit2.pbs
qsub kisumuf-fit2.pbs
qsub manicm-fit2.pbs
qsub manicf-fit2.pbs
qsub masakam-fit2.pbs
qsub masakaf-fit2.pbs
qsub rakaim-fit2.pbs
qsub rakaif-fit2.pbs
qsub umkhanm-fit2.pbs
qsub umkhanf-fit2.pbs

qsub agincm-fit3.pbs
qsub agincf-fit3.pbs
qsub karongam-fit3.pbs
qsub karongaf-fit3.pbs
qsub kisesam-fit3.pbs
qsub kisesaf-fit3.pbs
qsub kisumum-fit3.pbs
qsub kisumuf-fit3.pbs
qsub manicm-fit3.pbs
qsub manicf-fit3.pbs
qsub masakam-fit3.pbs
qsub masakaf-fit3.pbs
qsub rakaim-fit3.pbs
qsub rakaif-fit3.pbs
qsub umkhanm-fit3.pbs
qsub umkhanf-fit3.pbs

qsub agincm-fit4.pbs
qsub agincf-fit4.pbs
qsub karongam-fit4.pbs
qsub karongaf-fit4.pbs
qsub kisesam-fit4.pbs
qsub kisesaf-fit4.pbs
qsub kisumum-fit4.pbs
qsub kisumuf-fit4.pbs
qsub manicm-fit4.pbs
qsub manicf-fit4.pbs
qsub masakam-fit4.pbs
qsub masakaf-fit4.pbs
qsub rakaim-fit4.pbs
qsub rakaif-fit4.pbs
qsub umkhanm-fit4.pbs
qsub umkhanf-fit4.pbs

qsub agincm-fit5.pbs
qsub agincf-fit5.pbs
qsub karongam-fit5.pbs
qsub karongaf-fit5.pbs
qsub kisesam-fit5.pbs
qsub kisesaf-fit5.pbs
qsub kisumum-fit5.pbs
qsub kisumuf-fit5.pbs
qsub manicm-fit5.pbs
qsub manicf-fit5.pbs
qsub masakam-fit5.pbs
qsub masakaf-fit5.pbs
qsub rakaim-fit5.pbs
qsub rakaif-fit5.pbs
qsub umkhanm-fit5.pbs
qsub umkhanf-fit5.pbs

qsub agincm-fit6.pbs
qsub agincf-fit6.pbs
qsub karongam-fit6.pbs
qsub karongaf-fit6.pbs
qsub kisesam-fit6.pbs
qsub kisesaf-fit6.pbs
qsub kisumum-fit6.pbs
qsub kisumuf-fit6.pbs
qsub manicm-fit6.pbs
qsub manicf-fit6.pbs
qsub masakam-fit6.pbs
qsub masakaf-fit6.pbs
qsub rakaim-fit6.pbs
qsub rakaif-fit6.pbs
qsub umkhanm-fit6.pbs
qsub umkhanf-fit6.pbs

